"use client";

import { useState } from "react";
import { AlignLeft, CheckCircle2, CircleDot, ListChecks, SlidersHorizontal } from "lucide-react";
import { CHOICE_SLOTS, QUESTION_KINDS } from "./fields";

type QuestionKind = "SINGLE" | "MULTI" | "TRUEFALSE" | "SHORT";
type Choice = { textAr?: string; textEn?: string; correct?: boolean };
type RecordValue = { kind?: QuestionKind; textAr?: string; textEn?: string; explainAr?: string | null; explainEn?: string | null; points?: number; order?: number };

const KIND_META = {
  SINGLE: { icon: CircleDot, desc: "إجابة صحيحة واحدة" }, MULTI: { icon: ListChecks, desc: "أكثر من إجابة صحيحة" },
  TRUEFALSE: { icon: CheckCircle2, desc: "صواب أو خطأ" }, SHORT: { icon: AlignLeft, desc: "تصحيح يدوي" },
};

export function QuestionEditor({ record, choices = [] }: { record?: RecordValue; choices?: Choice[] }) {
  const [kind, setKind] = useState<QuestionKind>(record?.kind ?? "SINGLE");
  const [lang, setLang] = useState<"ar" | "en">("ar");
  const [correct, setCorrect] = useState(() => Array.from({ length: CHOICE_SLOTS }, (_, i) => Boolean(choices[i]?.correct)));
  const rows = kind === "TRUEFALSE" ? 2 : CHOICE_SLOTS;
  const markCorrect = (index: number) => setCorrect(current => current.map((value, i) => kind === "MULTI" ? (i === index ? !value : value) : i === index));

  return <div className="space-y-7">
    <section><div className="mb-3"><h2 className="text-[15px] font-extrabold text-navy-900">١. نوع السؤال</h2><p className="mt-1 text-[12px] text-ink-soft">اختر النوع المناسب؛ ستتغير خيارات الإجابة تلقائيًا.</p></div>
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{QUESTION_KINDS.map(option => { const value = option.value as QuestionKind; const Icon = KIND_META[value].icon; return <label key={value} className={`cursor-pointer rounded-xl border-2 p-3.5 transition ${kind === value ? "border-gold bg-gold/10 shadow-sm" : "border-black/5 bg-white hover:border-gold/40"}`}><input type="radio" name="kind" value={value} checked={kind === value} onChange={() => setKind(value)} className="sr-only"/><span className="flex items-center gap-2"><span className={`grid h-9 w-9 place-items-center rounded-lg ${kind === value ? "bg-gold text-navy-950" : "bg-slate-100 text-navy-700"}`}><Icon size={18}/></span><span><b className="block text-[13px] text-navy-900">{option.label}</b><small className="text-[10.5px] text-ink-soft">{KIND_META[value].desc}</small></span></span></label>; })}</div>
    </section>

    <section className="overflow-hidden rounded-2xl border border-black/10 bg-white"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-black/10 bg-slate-50 px-4 pt-4"><div className="pb-3"><h2 className="text-[15px] font-extrabold text-navy-900">٢. نص السؤال</h2><p className="mt-1 text-[11.5px] text-ink-soft">أدخل السؤال والتعليمات باللغتين.</p></div><div className="flex self-end"><button type="button" onClick={() => setLang("ar")} className={`border-b-2 px-4 py-3 text-[12px] font-bold ${lang === "ar" ? "border-gold text-navy-900" : "border-transparent text-ink-soft"}`}>العربية</button><button type="button" onClick={() => setLang("en")} className={`border-b-2 px-4 py-3 text-[12px] font-bold ${lang === "en" ? "border-gold text-navy-900" : "border-transparent text-ink-soft"}`}>English</button></div></div>
      <div className="p-5"><div className={lang === "ar" ? "space-y-4" : "hidden"}><label className="block"><span className="mb-1.5 block text-[12.5px] font-bold text-navy-900">نص السؤال <small className="font-normal text-ink-soft">(العربية أو الإنجليزية مطلوبة)</small></span><textarea name="textAr" defaultValue={record?.textAr} rows={4} dir="rtl" placeholder="اكتب السؤال هنا…" className="w-full rounded-xl border border-black/10 px-4 py-3 text-[14px] leading-7 outline-none focus:border-gold focus:ring-4 focus:ring-gold/15"/></label><label className="block"><span className="mb-1.5 block text-[12.5px] font-bold text-navy-900">شرح الإجابة بعد التسليم <small className="font-normal text-ink-soft">(اختياري)</small></span><textarea name="explainAr" defaultValue={record?.explainAr ?? ""} rows={2} dir="rtl" placeholder="لماذا هذه الإجابة صحيحة؟" className="w-full rounded-xl border border-black/10 px-4 py-3 text-[13px] leading-7 outline-none focus:border-gold"/></label></div>
        <div className={lang === "en" ? "space-y-4" : "hidden"}><label className="block"><span className="mb-1.5 block text-[12.5px] font-bold text-navy-900">Question text <small className="font-normal text-ink-soft">(optional translation)</small></span><textarea name="textEn" defaultValue={record?.textEn} rows={4} dir="ltr" placeholder="Type the question here…" className="w-full rounded-xl border border-black/10 px-4 py-3 text-[14px] leading-7 outline-none focus:border-gold focus:ring-4 focus:ring-gold/15"/></label><label className="block"><span className="mb-1.5 block text-[12.5px] font-bold text-navy-900">Answer explanation <small className="font-normal text-ink-soft">(optional)</small></span><textarea name="explainEn" defaultValue={record?.explainEn ?? ""} rows={2} dir="ltr" className="w-full rounded-xl border border-black/10 px-4 py-3 text-[13px] leading-7 outline-none focus:border-gold"/></label></div></div>
    </section>

    {kind !== "SHORT" && <section className="rounded-2xl border border-black/10 bg-cream-50/50 p-5"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-[15px] font-extrabold text-navy-900">٣. خيارات الإجابة</h2><p className="mt-1 text-[11.5px] text-ink-soft">{kind === "MULTI" ? "يمكن تحديد عدة إجابات صحيحة." : "حدد إجابة صحيحة واحدة."}</p></div><div className="inline-flex rounded-lg border border-black/10 bg-white p-1"><button type="button" onClick={() => setLang("ar")} className={`rounded-md px-3 py-1.5 text-[11px] font-bold ${lang === "ar" ? "bg-navy-900 text-white" : "text-ink-soft"}`}>عربي</button><button type="button" onClick={() => setLang("en")} className={`rounded-md px-3 py-1.5 text-[11px] font-bold ${lang === "en" ? "bg-navy-900 text-white" : "text-ink-soft"}`}>EN</button></div></div>
      <div className="space-y-2.5">{Array.from({length: rows}, (_, i) => <div key={i} className={`flex items-center gap-3 rounded-xl border p-2.5 transition ${correct[i] ? "border-emerald-300 bg-emerald-50" : "border-black/5 bg-white"}`}><button type="button" onClick={() => markCorrect(i)} className={`grid h-8 w-8 shrink-0 place-items-center rounded-full border-2 text-[13px] font-black ${correct[i] ? "border-emerald-600 bg-emerald-600 text-white" : "border-black/15 text-transparent"}`} aria-label="تحديد كإجابة صحيحة">✓</button><input type="checkbox" name={`choice_${i}_correct`} checked={correct[i]} readOnly className="sr-only"/><span className="w-5 text-center text-[11px] font-bold text-ink-soft">{i+1}</span><input name={`choice_${i}_ar`} defaultValue={choices[i]?.textAr ?? (kind === "TRUEFALSE" ? (i === 0 ? "صواب" : "خطأ") : "")} dir="rtl" placeholder="نص الخيار بالعربية" className={`min-w-0 flex-1 rounded-lg border border-black/10 px-3 py-2.5 text-[13px] outline-none focus:border-gold ${lang === "ar" ? "block" : "hidden"}`}/><input name={`choice_${i}_en`} defaultValue={choices[i]?.textEn ?? (kind === "TRUEFALSE" ? (i === 0 ? "True" : "False") : "")} dir="ltr" placeholder="Choice text in English" className={`min-w-0 flex-1 rounded-lg border border-black/10 px-3 py-2.5 text-[13px] outline-none focus:border-gold ${lang === "en" ? "block" : "hidden"}`}/>{correct[i] && <span className="hidden text-[11px] font-bold text-emerald-700 sm:block">صحيحة</span>}</div>)}</div>
    </section>}

    <section className="rounded-2xl border border-black/10 bg-white p-5"><div className="mb-4 flex items-center gap-2"><SlidersHorizontal size={17} className="text-gold-3"/><h2 className="text-[14px] font-extrabold text-navy-900">إعدادات السؤال</h2></div><div className="grid gap-4 sm:grid-cols-2"><label><span className="mb-1.5 block text-[12.5px] font-bold text-navy-900">درجة السؤال</span><input type="number" name="points" min="0" defaultValue={record?.points ?? 1} className="w-full rounded-xl border border-black/10 px-3.5 py-2.5 outline-none focus:border-gold"/></label><label><span className="mb-1.5 block text-[12.5px] font-bold text-navy-900">الترتيب <small className="font-normal text-ink-soft">(0 = في النهاية)</small></span><input type="number" name="order" min="0" defaultValue={record?.order ?? 0} className="w-full rounded-xl border border-black/10 px-3.5 py-2.5 outline-none focus:border-gold"/></label></div></section>
  </div>;
}
